# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders2',
            fields=[
                ('orderid', models.AutoField(db_column='orderId', primary_key=True, serialize=False)),
                ('orderdate', models.CharField(blank=True, db_column='orderDate', max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Orders2',
                'managed': False,
            },
        ),
    ]
