# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('request_type', models.CharField(blank=True, max_length=255, null=True)),
                ('parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('request_duration_ms', models.IntegerField(blank=True, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('request_ip_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'audit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_language', models.TextField(blank=True, db_column='accept-language', null=True)),
                ('postman_token', models.TextField(blank=True, db_column='postman-token', null=True)),
                ('host', models.TextField(blank=True, null=True)),
                ('connection', models.TextField(blank=True, null=True)),
                ('content_type', models.TextField(blank=True, db_column='content-type', null=True)),
                ('cache_control', models.TextField(blank=True, db_column='cache-control', null=True)),
                ('accept_encoding', models.TextField(blank=True, db_column='accept-encoding', null=True)),
                ('user_agent', models.TextField(blank=True, db_column='user-agent', null=True)),
                ('accept', models.TextField(blank=True, null=True)),
                ('ipaddress', models.TextField(blank=True, db_column='IpAddress', null=True)),
                ('time_to_respond', models.TextField(blank=True, db_column='Time to respond', null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
                ('url', models.TextField(blank=True, db_column='Url', null=True)),
                ('response_code', models.TextField(blank=True, db_column='Response Code', null=True)),
                ('test', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcode', models.CharField(blank=True, db_column='productCode', max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Bridge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bridge2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcode', models.CharField(blank=True, db_column='productCode', max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Bridge2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(db_column='categoryId', primary_key=True, serialize=False)),
                ('categorydescription', models.TextField(blank=True, db_column='categoryDescription', null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.AutoField(db_column='feedbackId', primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='orderId', primary_key=True, serialize=False)),
                ('orderdate', models.DateField(blank=True, db_column='orderDate', null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parameters2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField(blank=True, db_column='Parameters', null=True)),
                ('ipaddress', models.TextField(blank=True, db_column='IpAddress', null=True)),
                ('time_to_respond', models.IntegerField(blank=True, db_column='Time_to_respond', null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
                ('url', models.TextField(blank=True, db_column='Url', null=True)),
                ('response_code', models.IntegerField(blank=True, db_column='Response_Code', null=True)),
                ('request_type', models.CharField(blank=True, db_column='Request_type', max_length=11, null=True)),
            ],
            options={
                'db_table': 'Parameters2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productcode', models.CharField(db_column='productCode', max_length=255, primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, db_column='productName', max_length=255, null=True)),
                ('productdescription', models.TextField(blank=True, db_column='ProductDescription', null=True)),
                ('buyprice', models.CharField(blank=True, db_column='buyPrice', max_length=255, null=True)),
                ('display', models.IntegerField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=255)),
                ('product_description', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.AutoField(db_column='productId', primary_key=True, serialize=False)),
                ('productcode', models.CharField(blank=True, db_column='productCode', max_length=255, null=True)),
                ('productname', models.CharField(blank=True, db_column='productName', max_length=255, null=True)),
                ('productdescription', models.TextField(blank=True, db_column='productDescription', null=True)),
                ('buyprice', models.DecimalField(blank=True, db_column='buyPrice', decimal_places=2, max_digits=10, null=True)),
                ('quantityinstock', models.IntegerField(blank=True, db_column='quantityInStock', null=True)),
                ('enabled', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('customername', models.CharField(db_column='customerName', max_length=255, primary_key=True, serialize=False)),
                ('contactfirstname', models.CharField(blank=True, db_column='contactFirstName', max_length=255, null=True)),
                ('contactlastname', models.CharField(blank=True, db_column='contactLastName', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('addressline1', models.CharField(blank=True, db_column='addressLine1', max_length=255, null=True)),
                ('addressline2', models.CharField(blank=True, db_column='addressLine2', max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('customername', models.CharField(blank=True, db_column='customerName', max_length=255, null=True)),
                ('contactfirstname', models.CharField(blank=True, db_column='contactFirstName', max_length=255, null=True)),
                ('contactlastname', models.CharField(blank=True, db_column='contactLastName', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('addressline1', models.CharField(blank=True, db_column='addressLine1', max_length=255, null=True)),
                ('addressline2', models.CharField(blank=True, db_column='addressLine2', max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
